# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               ewrfedf
tagline:             'Android Dev'
description:         '<a href="http://ewrfedf.github.io/" target="_blank">Android Dev</a>.'
url:                 http://ewrfedf.github.io/
baseurl:             /
paginate:            5

# About/contact
author:
  name:              ewrfedf
  url:               http://ewrfedf.github.io/
  email:             zhengcp9@gmail.com

# Custom vars
version:             1.0.0
