# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ewrfedf 
description:      'I am Android Developer. This is my personal blog,some are orgin , some are tranlation. Also I'm from cn'
url:              http://ewrfedf.github.io 
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'ewerfedf'
  url:            http://ewrfedf.github.io 
 

paginate:         5

disqus_shortname: ewrfedf 

github:
  repo:           https://github.com/ewrfedf 

gems:
  - jekyll-sitemap

twitter: '@chrisbanes'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
