# Dependencies 
markdown:         kramdown
highlighter:      pygments
 
# Setup
title:            ewrfedf
description:      'Android Devloper Life Record'
url:              http://ewrfedf.github.io
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'ewrfedf'
  url:            http://ewrfedf.github.io

paginate:         5

disqus_shortname: chrisbanes

github:
  repo:           https://github.com/ewrfedf

gems:
  - jekyll-sitemap
  - jekyll-paginate

twitter: '@chrisbanes'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
